# Generated by Django 3.0.5 on 2020-04-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200404_2156'),
        ('product', '0012_category_slug'),
        ('product', '0010_category_slug'),
    ]

    operations = [
    ]
